
package com.sinosoft.module.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-17T10:34:07.179+08:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "getFireUserInfoFault", targetNamespace = "http://ws.module.sinosoft.com/xsd")
public class GetFireUserInfoFault extends Exception {

    private com.sinosoft.module.ws.xsd.GetFireUserInfoFault getFireUserInfoFault;

    public GetFireUserInfoFault() {
        super();
    }

    public GetFireUserInfoFault(String message) {
        super(message);
    }

    public GetFireUserInfoFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetFireUserInfoFault(String message, com.sinosoft.module.ws.xsd.GetFireUserInfoFault getFireUserInfoFault) {
        super(message);
        this.getFireUserInfoFault = getFireUserInfoFault;
    }

    public GetFireUserInfoFault(String message, com.sinosoft.module.ws.xsd.GetFireUserInfoFault getFireUserInfoFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getFireUserInfoFault = getFireUserInfoFault;
    }

    public com.sinosoft.module.ws.xsd.GetFireUserInfoFault getFaultInfo() {
        return this.getFireUserInfoFault;
    }
}
