package com.sinosoft.module.ws;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-17T10:34:07.189+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://ws.module.sinosoft.com", name = "serverWSPortType")
@XmlSeeAlso({com.sinosoft.module.ws.xsd.ObjectFactory.class})
public interface ServerWSPortType {

    @WebMethod(action = "urn:getCorpResult")
    @Action(input = "urn:getCorpResult")
    @RequestWrapper(localName = "getCorpResult", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetCorpResult")
    @ResponseWrapper(localName = "getCorpResultResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetCorpResultResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String getCorpResult(
        @WebParam(name = "signMark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signMark,
        @WebParam(name = "signStr", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signStr,
        @WebParam(name = "mark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String mark
    );

    @WebMethod(action = "urn:findLableFlowInfo")
    @Action(input = "urn:findLableFlowInfo")
    @RequestWrapper(localName = "findLableFlowInfo", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.FindLableFlowInfo")
    @ResponseWrapper(localName = "findLableFlowInfoResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.FindLableFlowInfoResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String findLableFlowInfo(
        @WebParam(name = "labelId", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String labelId,
        @WebParam(name = "deptId", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String deptId,
        @WebParam(name = "productName", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String productName
    );

    @WebMethod(action = "urn:getTipstaffResult")
    @Action(input = "urn:getTipstaffResult")
    @RequestWrapper(localName = "getTipstaffResult", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetTipstaffResult")
    @ResponseWrapper(localName = "getTipstaffResultResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetTipstaffResultResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String getTipstaffResult(
        @WebParam(name = "signMark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signMark,
        @WebParam(name = "signStr", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signStr,
        @WebParam(name = "mark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String mark
    );

    @WebMethod(action = "urn:getLabelInfoByCode")
    @Action(input = "urn:getLabelInfoByCode")
    @RequestWrapper(localName = "getLabelInfoByCode", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetLabelInfoByCode")
    @ResponseWrapper(localName = "getLabelInfoByCodeResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetLabelInfoByCodeResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String getLabelInfoByCode(
        @WebParam(name = "labelCode", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String labelCode
    );

    @WebMethod(operationName = "notifyServerDelFile_new", action = "urn:notifyServerDelFile_new")
    @Action(input = "urn:notifyServerDelFile_new")
    @RequestWrapper(localName = "notifyServerDelFile_new", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.NotifyServerDelFileNew")
    @ResponseWrapper(localName = "notifyServerDelFile_newResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.NotifyServerDelFileNewResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String notifyServerDelFileNew(
        @WebParam(name = "signMark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signMark,
        @WebParam(name = "signStr", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signStr,
        @WebParam(name = "downloadMark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String downloadMark
    );

    @WebMethod(operationName = "downloadOnline_new", action = "urn:downloadOnline_new")
    @Action(input = "urn:downloadOnline_new")
    @RequestWrapper(localName = "downloadOnline_new", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.DownloadOnlineNew")
    @ResponseWrapper(localName = "downloadOnline_newResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.DownloadOnlineNewResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String downloadOnlineNew(
        @WebParam(name = "signMark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signMark,
        @WebParam(name = "signStr", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signStr,
        @WebParam(name = "ruleContent", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        byte[] ruleContent
    );

    @WebMethod(action = "urn:getProjectLog")
    @Action(input = "urn:getProjectLog")
    @RequestWrapper(localName = "getProjectLog", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetProjectLog")
    @ResponseWrapper(localName = "getProjectLogResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetProjectLogResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String getProjectLog(
        @WebParam(name = "signMark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signMark,
        @WebParam(name = "signStr", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signStr
    );

    @WebMethod(action = "urn:getFireUserInfo")
    @Action(input = "urn:getFireUserInfo", fault = {})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getFireUserInfoResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", partName = "part1")
    public com.sinosoft.module.ws.xsd.GetFireUserInfoResponse getFireUserInfo() throws GetFireUserInfoFault;

    @WebMethod(operationName = "getRandomSignText_new", action = "urn:getRandomSignText_new")
    @Action(input = "urn:getRandomSignText_new")
    @RequestWrapper(localName = "getRandomSignText_new", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetRandomSignTextNew")
    @ResponseWrapper(localName = "getRandomSignText_newResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetRandomSignTextNewResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String getRandomSignTextNew(
        @WebParam(name = "mark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String mark
    );

    @WebMethod(action = "urn:updateQueryLable1")
    @Action(input = "urn:updateQueryLable1")
    @Oneway
    @RequestWrapper(localName = "updateQueryLable1", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.UpdateQueryLable1")
    public void updateQueryLable1(
        @WebParam(name = "ipAddress", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String ipAddress,
        @WebParam(name = "lableId", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String lableId
    );

    @WebMethod(operationName = "getUnitData_new", action = "urn:getUnitData_new")
    @Action(input = "urn:getUnitData_new")
    @RequestWrapper(localName = "getUnitData_new", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetUnitDataNew")
    @ResponseWrapper(localName = "getUnitData_newResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetUnitDataNewResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String getUnitDataNew(
        @WebParam(name = "signMark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signMark,
        @WebParam(name = "signStr", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signStr,
        @WebParam(name = "date", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String date
    );

    @WebMethod(action = "urn:onlineCheck")
    @Action(input = "urn:onlineCheck", fault = {})
    @RequestWrapper(localName = "onlineCheck", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.OnlineCheck")
    @ResponseWrapper(localName = "onlineCheckResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.OnlineCheckResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String onlineCheck(
        @WebParam(name = "userId", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String userId,
        @WebParam(name = "deptId", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String deptId,
        @WebParam(name = "labelCode", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String labelCode
    ) throws OnlineCheckFault;

    @WebMethod(action = "urn:getClientVer")
    @Action(input = "urn:getClientVer")
    @RequestWrapper(localName = "getClientVer", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetClientVer")
    @ResponseWrapper(localName = "getClientVerResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetClientVerResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String getClientVer(
        @WebParam(name = "ver", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String ver
    );

    @WebMethod(action = "urn:existsUserPhone")
    @Action(input = "urn:existsUserPhone")
    @RequestWrapper(localName = "existsUserPhone", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.ExistsUserPhone")
    @ResponseWrapper(localName = "existsUserPhoneResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.ExistsUserPhoneResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.Boolean existsUserPhone(
        @WebParam(name = "userPhone", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String userPhone
    );

    @WebMethod(operationName = "getList_new", action = "urn:getList_new")
    @Action(input = "urn:getList_new")
    @RequestWrapper(localName = "getList_new", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetListNew")
    @ResponseWrapper(localName = "getList_newResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.GetListNewResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public byte[] getListNew(
        @WebParam(name = "signMark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signMark,
        @WebParam(name = "signStr", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signStr,
        @WebParam(name = "xmlList", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        byte[] xmlList
    );

    @WebMethod(operationName = "reUpload_new", action = "urn:reUpload_new")
    @Action(input = "urn:reUpload_new")
    @RequestWrapper(localName = "reUpload_new", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.ReUploadNew")
    @ResponseWrapper(localName = "reUpload_newResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.ReUploadNewResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String reUploadNew(
        @WebParam(name = "mark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String mark,
        @WebParam(name = "signStr", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signStr,
        @WebParam(name = "content", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        byte[] content
    );

    @WebMethod(operationName = "upload_new", action = "urn:upload_new")
    @Action(input = "urn:upload_new")
    @RequestWrapper(localName = "upload_new", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.UploadNew")
    @ResponseWrapper(localName = "upload_newResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.UploadNewResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String uploadNew(
        @WebParam(name = "mark", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String mark,
        @WebParam(name = "signStr", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String signStr,
        @WebParam(name = "content", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        byte[] content
    );

    @WebMethod(action = "urn:isSuedUsbKey")
    @Action(input = "urn:isSuedUsbKey")
    @RequestWrapper(localName = "isSuedUsbKey", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.IsSuedUsbKey")
    @ResponseWrapper(localName = "isSuedUsbKeyResponse", targetNamespace = "http://ws.module.sinosoft.com/xsd", className = "com.sinosoft.module.ws.xsd.IsSuedUsbKeyResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.module.sinosoft.com/xsd")
    public java.lang.String isSuedUsbKey(
        @WebParam(name = "deptid", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String deptid,
        @WebParam(name = "deptName", targetNamespace = "http://ws.module.sinosoft.com/xsd")
        java.lang.String deptName
    );
}
